#*****************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# design.tcl: Tcl script for re-creating project 'softmax_pynq'
#
# Generated by Vivado on Thu Nov 01 18:02:02 +0800 2018
# IP Build 2085800 on Fri Dec 15 22:25:07 MST 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (design.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/axi_m_2.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/fix_shift.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/myrom4bit.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/myrom5bit.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/custom_register.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/myslice.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/btn_triggle.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/clk_div.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/reg4.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/w_1_combine.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/reg62.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/shift_r2.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/w2_combine.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/reg3.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/switch_16_8.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/bd/design_1/design_1.bd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/some_reg/reg64.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/axi_s_cntrol.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/myresigter.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/not_gate.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/myconcat.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/DW_mult_4.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/some_reg/reg5.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/mypack.vhd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/cond_add.vhd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/nr_r4_cel.vhd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/div_r4_pipe.vhd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/summary.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/verilog/div_us.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/division.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/bd/design_2/design_2.bd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/bd/design_3/design_3.bd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/bd/design_3/hdl/design_3_wrapper.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/negedge_detect.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/AXI_M.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/data_distribute.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/capture_local_result.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/get_result.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/edge_detect.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/substrate.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/bd/axi_test/axi_test.bd"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/verilog/div_su.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/verilog/div_uu.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/verilog/div.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/new/MUL_TOP.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sources_1/imports/rev_4/mul_16.edf"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/constrs_1/new/successful.xdc"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sim_1/new/design2.v"
#    "F:/FPGA/soft3/softmax3_V1_0/softmax_pynq/softmax_pynq.srcs/sim_1/imports/softmax3_0/design_1_wrapper_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [info script]]

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set project_name "softmax_pynq"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set project_name $::user_project_name
}

variable script_file
set script_file "design.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set project_name [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
# set orig_proj_dir "[file normalize "$origin_dir/src]"

# Create project
create_project ${project_name} ./${project_name} -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "www.digilentinc.com:pynq-z1:part0:1.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${project_name}.cache/ip" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo/axi_ip"] [file normalize "$origin_dir/ip_repo/dwip"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/axi_m_2.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/fix_shift.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/myrom4bit.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/myrom5bit.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/custom_register.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/myslice.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/btn_triggle.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/clk_div.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/reg4.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/w_1_combine.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/reg62.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/shift_r2.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/w2_combine.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/reg3.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/switch_16_8.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/bd/design_1/design_1.bd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/some_reg/reg64.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/axi_s_cntrol.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/myresigter.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/not_gate.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/myconcat.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/DW_mult_4.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/some_reg/reg5.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/mypack.vhd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/cond_add.vhd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/nr_r4_cel.vhd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/div_pipe_r4_arch2/div_r4_pipe.vhd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/summary.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/verilog/div_us.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/division.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/bd/design_2/design_2.bd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/bd/design_3/design_3.bd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/bd/design_3/hdl/design_3_wrapper.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/negedge_detect.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/AXI_M.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/data_distribute.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/capture_local_result.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/get_result.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/edge_detect.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/substrate.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/bd/axi_test/axi_test.bd"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/verilog/div_su.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/verilog/div_uu.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/verilog/div.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/new/MUL_TOP.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sources_1/imports/rev_4/mul_16.edf"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "div_pipe_r4_arch2/mypack.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "div_pipe_r4_arch2/cond_add.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "div_pipe_r4_arch2/nr_r4_cel.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "div_pipe_r4_arch2/div_r4_pipe.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "hdl/design_2_wrapper.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/division.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "design_2/design_2.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "design_3/design_3.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "hdl/design_3_wrapper.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/negedge_detect.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/AXI_M.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/data_distribute.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/capture_local_result.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/get_result.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/edge_detect.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "new/substrate.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "axi_test/axi_test.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj

set file "rev_4/mul_16.edf"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "EDIF" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "design_1_wrapper" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/softmax_pynq.srcs/constrs_1/new/successful.xdc"]"
set file_imported [import_files -fileset constrs_1 $file]
set file "new/successful.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "$proj_dir/$project_name.srcs/constrs_1/new/successful.xdc" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sim_1/new/design2.v"]"\
 "[file normalize "$origin_dir/src/softmax_pynq.srcs/sim_1/imports/softmax3_0/design_1_wrapper_behav.wcfg"]"\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "deisgn2" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# Create 'synth_2' run (if not found)
if {[string equal [get_runs -quiet synth_2] ""]} {
    create_run -name synth_2 -part xc7z020clg400-1 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_2]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_2]
}
set obj [get_runs synth_2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_2_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_2] synth_2_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_2_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_2
}
set obj [get_report_configs -of_objects [get_runs synth_2] synth_2_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_2]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_2]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# Create 'impl_2' run (if not found)
if {[string equal [get_runs -quiet impl_2] ""]} {
    create_run -name impl_2 -part xc7z020clg400-1 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_2
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_2]
  set_property flow "Vivado Implementation 2017" [get_runs impl_2]
}
set obj [get_runs impl_2]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_2_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_2_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0] "" ] } {
  create_report_config -report_name impl_2_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_2_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_2_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_2_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_2_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_2_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_2_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_2_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0] "" ] } {
  create_report_config -report_name impl_2_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_2_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_2_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_2_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_2_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_2_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_2_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_2
}
set obj [get_report_configs -of_objects [get_runs impl_2] impl_2_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
set obj [get_runs impl_2]
set_property -name "needs_refresh" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_2]

puts "INFO: Project created:$project_name"
